project_name: nomad-minimal
run_name: nomad-minimal-lr1e-3

# training setup
use_wandb: True # set to false if you don't want to log to wandb
train: True
batch_size: 64
epochs: 10
gpu_ids: [0]
num_workers: 16
lr: 1e-3
optimizer: adamw
clipping: False
max_norm: 1.
scheduler: "cosine"
warmup: True 
warmup_epochs: 1
cyclic_period: 10
plateau_patience: 3
plateau_factor: 0.5
seed: 0

# model params
model_type: nomad
encoding_size: 256
# vision enc
vision_encoder: nomad_vint
obs_encoder: efficientnet-b0
# vision transformer
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
# denoiser
down_dims: [256, 384, 512]
attn_unet: False
cond_predict_scale: False

# diffusion model params
input_dims: 48
num_diffusion_iters: 10

# mask 
goal_mask_prob: 0.5

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 3 # 5
alpha: 1e-4

# distance bounds for distance and action and distance predictions 
distance:
  min_dist_cat: 0
  max_dist_cat: 20
action:
  min_dist_cat: 3
  max_dist_cat: 20

# action output params
len_traj_pred: 8


# dataset specific parameters
image_size: [224, 224] # width, height
datasets:
  nymeria:
    data_folder: /scratch/anw2067/nymeria
    train: data_splits/nymeria/train/
    test: data_splits/nymeria/test/
    action_stats:
      min: [-2.5, -2.5, -2.5, -3.14159, -3.14159, -3.14159]
      max: [1.5, 1.5, 1.5, 3.14159, 3.14159, 3.14159]
    gaussian_normalization_stats_path: "/home/anw2067/visualnav-transformer/train/nymeria_nomad_mean_var_stats.json"

# logging stuff
## =0 turns off
print_log_freq: 500 # in iterations
image_log_freq: 1000 #0 # in iterations
num_images_log: 8 #0 
pairwise_test_freq: 0 # in epochs
eval_fraction: 0.25
wandb_log_freq: 50 # in iterations
eval_freq: 1 # in epochs

eval_batch_size: 128